"use client";

/**
 * @amber-capability tempo.sync
 * @amber-doc Data portability interface exposing JSON export, JSON import (with optional replace), and full data clear via src/lib/sync, surfaced to the user on the Settings page alongside a theme toggle.
 */

import { useRef, useState } from "react";
import { Button } from "@/components/shared/ui";
import { ThemeToggle } from "@/components/settings/ThemeToggle";
import { clearAllData, exportData, importData, serializeData } from "@/lib/sync";
import { refresh } from "@/lib/state/store";

export default function SettingsPage() {
  const fileRef = useRef<HTMLInputElement>(null);
  const [msg, setMsg] = useState<string>("");

  const handleExport = async () => {
    const data = await exportData();
    const blob = new Blob([serializeData(data)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `tempo-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setMsg("Exported.");
  };

  const handleImport = async (replace: boolean) => {
    const file = fileRef.current?.files?.[0];
    if (!file) {
      setMsg("Pick a JSON file first.");
      return;
    }
    const text = await file.text();
    const result = await importData(text, { replace });
    if (!result.ok) {
      setMsg(`Import failed: ${result.reason}`);
      return;
    }
    await refresh();
    setMsg(`Imported ${result.counts?.sessions ?? 0} sessions, ${result.counts?.pieces ?? 0} pieces.`);
  };

  const handleClear = async () => {
    if (!confirm("Erase ALL data? This cannot be undone.")) return;
    if (!confirm("Really? Last chance — export a backup first.")) return;
    await clearAllData();
    await refresh();
    setMsg("All data cleared.");
  };

  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-3xl font-semibold tracking-tight">Settings</h1>
        <p className="text-sm text-[color:var(--muted)] mt-1">Theme, data portability, and the basics.</p>
      </header>

      <section className="card p-6 space-y-3">
        <h2 className="text-base font-semibold">Theme</h2>
        <p className="text-sm text-[color:var(--muted)]">Pick a mood. System follows your OS.</p>
        <ThemeToggle />
      </section>

      <section className="card p-6 space-y-4">
        <h2 className="text-base font-semibold">Backup & restore</h2>
        <p className="text-sm text-[color:var(--muted)]">Everything lives in this browser's IndexedDB. Export a JSON snapshot to back up or move devices.</p>
        <div className="flex flex-wrap gap-2">
          <Button onClick={handleExport}>Download JSON</Button>
        </div>
        <div className="space-y-2 pt-2">
          <input ref={fileRef} type="file" accept="application/json" className="text-sm" />
          <div className="flex gap-2">
            <Button onClick={() => handleImport(false)}>Merge import</Button>
            <Button onClick={() => handleImport(true)}>Replace all</Button>
          </div>
        </div>
        {msg && <div className="text-sm text-[color:var(--accent)] pt-2">{msg}</div>}
      </section>

      <section className="card p-6 space-y-3 border-[color:var(--rose)]/40">
        <h2 className="text-base font-semibold">Danger zone</h2>
        <p className="text-sm text-[color:var(--muted)]">Erase every instrument, piece, session and goal. There's no undo.</p>
        <Button variant="danger" onClick={handleClear}>Clear all data</Button>
      </section>

      <section className="card p-6 space-y-2">
        <h2 className="text-base font-semibold">About</h2>
        <p className="text-sm text-[color:var(--muted)]">
          Tempo is a local-first practice tracker for hobby musicians. MIT licensed.
        </p>
        <p className="text-sm text-[color:var(--muted)]">
          Architecture analyzed by <span className="text-[color:var(--text)]">prism0x2A</span> · stakeholder content generated by <span className="text-[color:var(--text)]">forge0x2B</span>.
        </p>
      </section>
    </div>
  );
}
